{
 "title": "GPU Utilization Statistics",
 "description": "A Visualization tool to observe the GPU Utilization Insights",
 "tags": [
  "Nvidia",
  "DCGM Exporter",
  "Infrastructure",
  "GPU",
  "Cluster",
  "Devops"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# GPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nvidia_smi_gpu_info", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{instance =\"10.150.0.3:9835\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nvidia_smi_gpu_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nvidia_smi_gpu_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vBios",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nvidia_smi_gpu_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Avg. SM Clock",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_SM_CLOCK", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "GPU Avg. Power ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Util",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_MEM_COPY_UTIL", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "GPU Mem Util",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED / (DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization (VRAM)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED / (DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE)",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Total Energy Consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "GPU NVLink Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU SM Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_SM_CLOCK", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_MEM_CLOCK", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_MEM_COPY_UTIL", "legendFormat": "{{modelName}}" }
   ]
  }
 ]
}